# Generated by Django 5.2 on 2025-04-09 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="Учреждение"),
                ),
                ("region", models.CharField(max_length=50, verbose_name="Регион")),
                ("address", models.CharField(max_length=50, verbose_name="Адрес")),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Год",
                    ),
                ),
                (
                    "inter_budget_transfer_amount",
                    models.IntegerField(
                        verbose_name="Размер иного межбюджетного трансферта руб"
                    ),
                ),
            ],
            options={
                "verbose_name": "Библиотека",
                "verbose_name_plural": "Библиотеки",
            },
        ),
    ]
